lithia_project:
  outputs:
    dev:
      account: KIFGRRR-FLB23697
      database: C2C_DEV
      password: Bharathmiz@3696
      role: ACCOUNTADMIN
      schema: RAW
      threads: 1
      type: snowflake
      user: AZURETRAINING
      warehouse: COMPUTE_WH
  target: dev
