name: lithia_project
version: '1.0.0'
config-version: 2

profile: 'lithia_project'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  lithia_project:
    +database: EDW_DEV
    +materialized: view  # Default materialization; can be overridden per model

    account:
      raw:
        +schema: RAW
      staging:
        +schema: STAGING
      etl:
        +schema: ETL
        +materialized: incremental

    sales:
      raw:
        +schema: RAW
      staging:
        +schema: STAGING
      etl:
        +schema: ETL
        +materialized: incremental
